const List<Map<String, String>> algerianWilayas = [
  {'wilaya_name_ascii': 'Adrar'},
  {'wilaya_name_ascii': 'Aïn Defla'},
  {'wilaya_name_ascii': 'Aïn Témouchent'},
  {'wilaya_name_ascii': 'Alger'},
  {'wilaya_name_ascii': 'Annaba'},
  {'wilaya_name_ascii': 'Batna'},
  {'wilaya_name_ascii': 'Béchar'},
  {'wilaya_name_ascii': 'Béjaïa'},
  {'wilaya_name_ascii': 'Biskra'},
  {'wilaya_name_ascii': 'Blida'},
  {'wilaya_name_ascii': 'Bordj Bou Arréridj'},
  {'wilaya_name_ascii': 'Bouira'},
  {'wilaya_name_ascii': 'Boumerdès'},
  {'wilaya_name_ascii': 'Chlef'},
  {'wilaya_name_ascii': 'Constantine'},
  {'wilaya_name_ascii': 'Djelfa'},
  {'wilaya_name_ascii': 'El Bayadh'},
  {'wilaya_name_ascii': 'El Oued'},
  {'wilaya_name_ascii': 'El Tarf'},
  {'wilaya_name_ascii': 'Ghardaïa'},
  {'wilaya_name_ascii': 'Guelma'},
  {'wilaya_name_ascii': 'Illizi'},
  {'wilaya_name_ascii': 'Jijel'},
  {'wilaya_name_ascii': 'Khenchela'},
  {'wilaya_name_ascii': 'Laghouat'},
  {'wilaya_name_ascii': 'Mascara'},
  {'wilaya_name_ascii': 'Médéa'},
  {'wilaya_name_ascii': 'Mila'},
  {'wilaya_name_ascii': 'Mostaganem'},
  {'wilaya_name_ascii': 'Msila'},
  {'wilaya_name_ascii': 'Naama'},
  {'wilaya_name_ascii': 'Oran'},
  {'wilaya_name_ascii': 'Ouargla'},
  {'wilaya_name_ascii': 'Oum el Bouaghi'},
  {'wilaya_name_ascii': 'Relizane'},
  {'wilaya_name_ascii': 'Saïda'},
  {'wilaya_name_ascii': 'Sétif'},
  {'wilaya_name_ascii': 'Sidi Bel Abbès'},
  {'wilaya_name_ascii': 'Skikda'},
  {'wilaya_name_ascii': 'Souk Ahras'},
  {'wilaya_name_ascii': 'Tamanghasset'},
  {'wilaya_name_ascii': 'Tébessa'},
  {'wilaya_name_ascii': 'Tiaret'},
  {'wilaya_name_ascii': 'Tindouf'},
  {'wilaya_name_ascii': 'Tipaza'},
  {'wilaya_name_ascii': 'Tissemsilt'},
  {'wilaya_name_ascii': 'Tizi Ouzou'}
];
